import { upload } from 'https://esm.sh/@vercel/blob@2.8.0/client?bundle';

const $ = (selector) => document.querySelector(selector);
const escape = (value = '') => String(value).replace(/[&<>'"]/g, (character) => ({ '&':'&amp;', '<':'&lt;', '>':'&gt;', "'":'&#39;', '"':'&quot;' })[character]);
const mimeFor = (file) => file.type || ({ mp3:'audio/mpeg', wav:'audio/wav', pdf:'application/pdf', jpg:'image/jpeg', jpeg:'image/jpeg', png:'image/png', webp:'image/webp' }[file.name.split('.').pop().toLowerCase()] || 'application/octet-stream');
const safeFilename = (name) => name.replace(/[^a-zA-Z0-9._-]/g, '-').slice(-100);
async function request(url, options = {}) { const response = await fetch(url, options); const data = await response.json().catch(() => ({})); if (!response.ok) throw new Error(data.error || 'Request failed.'); return data; }
function notice(selector, message, ok = false) { const node = $(selector); node.textContent = message; node.classList.toggle('ok', ok); }
function date(value) { return value ? new Date(value).toLocaleString('ko-KR') : '—'; }
function syncAccessTypeForm() { const reusable = $('#access-type')?.value === 'VALID_UNTIL'; const expiry = $('#expires-at'); if (!expiry) return; expiry.required = reusable; $('#expiry-label').textContent = reusable ? '(required)' : '(optional)'; $('#expiry-help').textContent = reusable ? 'VALID UNTIL DATE requires a future expiry date and supports re-login until then.' : 'ONE-TIME access can optionally have an expiry date.'; }

async function uploadPrivateFile(file, prefix, intent, noticeId) {
  if (!file) throw new Error('Choose a file first.');
  try {
    return await upload(`${prefix}${crypto.randomUUID()}-${safeFilename(file.name)}`, file, { access:'private', contentType:mimeFor(file), handleUploadUrl:'/api/upload', clientPayload:JSON.stringify(intent), multipart:file.size > 100 * 1024 * 1024, onUploadProgress:({ percentage }) => notice(noticeId, `Uploading securely… ${Math.round(percentage)}%`) });
  } catch (error) {
    // Preserve enough context in the administrator's browser console to correlate
    // with the redacted server diagnostic, without exposing token material in the UI.
    console.error('NOVA_BLOB_CLIENT_UPLOAD_FAILURE', { status: error?.status || error?.response?.status || null, message: error?.message || 'Unknown client upload failure', response: error?.response?.body || error?.response?.data || null });
    throw new Error('Private upload authorization failed. Please try again; if it persists, contact the site administrator.');
  }
}
async function refresh() {
  const [codes, music, global] = await Promise.all([request('/api/admin/codes'), request('/api/admin/music'), request('/api/admin/global')]);
  const dashboard = codes.dashboard;
  $('#metrics').innerHTML = `<div class="metric"><span class="tag">Access codes</span><strong>${dashboard.codes.reduce((total, item) => total + item.count, 0)}</strong></div><div class="metric"><span class="tag">Music tracks</span><strong>${dashboard.musicCount}</strong></div><div class="metric"><span class="tag">Global reps</span><strong>${dashboard.globalCount}</strong></div>`;
  $('#codes').innerHTML = codes.codes.length ? codes.codes.map((code) => `<div class="row"><div><strong>${escape(code.investor_label)}</strong><small>${escape(code.company || '—')} · ${escape(code.access_type === 'VALID_UNTIL' ? 'VALID UNTIL DATE' : 'ONE-TIME')} · ${escape(code.status)} · Exp. ${date(code.expires_at)}</small></div>${['UNUSED','ACTIVE_SESSION'].includes(code.status) ? `<button class="button danger revoke-code" type="button" data-id="${code.id}">Revoke</button>` : ''}</div>`).join('') : '<p class="helper">No codes yet.</p>';
  $('#music').innerHTML = music.tracks.length ? music.tracks.map((track) => `<div class="row"><div><strong>${escape(track.title)}</strong><small>${escape(track.category)} · ${escape(track.genre || 'No genre')} · ${track.slug ? `Slug: ${escape(track.slug)}` : 'No QR slug'} · ${track.is_active ? 'Active' : 'Hidden'}</small></div><div><button class="button secondary edit-music" type="button" data-id="${track.id}" data-title="${escape(track.title)}" data-genre="${escape(track.genre || '')}" data-slug="${escape(track.slug || '')}">Edit</button> <button class="button secondary replace-music" type="button" data-id="${track.id}">Replace file</button> <button class="button danger delete-music" type="button" data-id="${track.id}">Delete</button></div></div>`).join('') : '<p class="helper">No music yet.</p>';
  $('#global').innerHTML = global.representatives.length ? global.representatives.map((rep) => `<div class="row"><div><strong>${escape(rep.country)} ${rep.name ? `· ${escape(rep.name)}` : ''}</strong><small>${escape(rep.role || 'No role')} · PDF ${rep.has_profile_pdf ? 'ready' : 'missing'}</small></div><div><button class="button secondary edit-global" data-id="${rep.id}" data-country="${escape(rep.country)}" data-name="${escape(rep.name || '')}">Edit</button> <button class="button secondary replace-profile-pdf" data-id="${rep.id}">Replace PDF</button> <button class="button secondary replace-profile-photo" data-id="${rep.id}">Replace photo</button> <button class="button danger delete-global" data-id="${rep.id}">Delete</button></div></div>`).join('') : '<p class="helper">No representatives yet.</p>';
}
async function enterApp(me) { $('#admin-login').classList.add('hidden'); $('#admin-app').classList.remove('hidden'); $('#admin-email').textContent = me.admin.email; await refresh(); }
function replaceFile(button) { const isMusic = button.matches('.replace-music'); const isPdf = button.matches('.replace-profile-pdf'); const input = document.createElement('input'); input.type = 'file'; input.accept = isMusic ? 'audio/mpeg,audio/mp3,audio/wav' : isPdf ? 'application/pdf' : 'image/jpeg,image/png,image/webp'; input.addEventListener('change', async () => { const file = input.files[0]; if (!file) return; const kind = isMusic ? 'music-replace' : isPdf ? 'global-pdf-replace' : 'global-photo-replace'; const prefix = isMusic ? 'investor-room/music/' : isPdf ? 'investor-room/global-profiles/' : 'investor-room/global-photos/'; const noticeId = isMusic ? '#music-notice' : '#global-notice'; try { await uploadPrivateFile(file, prefix, { kind, targetId: button.dataset.id }, noticeId); notice(noticeId, 'Private replacement completed. Library is updating…', true); setTimeout(refresh, 1200); } catch (error) { notice(noticeId, error.message); } }); input.click(); }

$('#login-form').addEventListener('submit', async (event) => { event.preventDefault(); const form = event.currentTarget; const button = form.querySelector('button'); button.disabled = true; try { await request('/api/auth?role=admin&action=login', { method:'POST', headers:{'Content-Type':'application/json'}, body:JSON.stringify(Object.fromEntries(new FormData(form))) }); await enterApp(await request('/api/auth?role=admin&action=session')); } catch (error) { notice('#login-notice', error.message); } finally { button.disabled = false; } });
$('#access-type')?.addEventListener('change', syncAccessTypeForm); syncAccessTypeForm();
$('#code-form').addEventListener('submit', async (event) => { event.preventDefault(); const form = event.currentTarget; const button = form?.querySelector('button[type="submit"]'); if (!form || typeof form.reset !== 'function') { notice('#code-notice', 'The access-code form is unavailable. Reload the page and try again.'); return; } if (button) button.disabled = true; let codeCreated = false; try { const payload = Object.fromEntries(new FormData(form)); if (payload.accessType === 'VALID_UNTIL' && !payload.expiresAt) throw new Error('A future expiration date is required for reusable access.'); if (payload.expiresAt) { const expiry = new Date(payload.expiresAt); if (Number.isNaN(expiry.getTime())) throw new Error('Enter a valid expiration date.'); payload.expiresAt = expiry.toISOString(); } const data = await request('/api/admin/codes', { method:'POST', headers:{'Content-Type':'application/json'}, body:JSON.stringify(payload) }); const accessCode = String(data?.code?.value || ''); if (!accessCode) throw new Error('Missing access code response.'); codeCreated = true; notice('#code-notice', `New code (copy now): ${accessCode}`, true); form.reset(); syncAccessTypeForm(); try { await refresh(); } catch { notice('#code-notice', `New code (copy now): ${accessCode}. The dashboard will refresh when reloaded.`, true); } } catch (error) { if (!codeCreated) notice('#code-notice', error.message || 'Unable to create an access code. Check the form details and try again.'); } finally { if (button) button.disabled = false; } });
$('#music-form').addEventListener('submit', async (event) => { event.preventDefault(); const form = event.currentTarget; const button = form.querySelector('button'); button.disabled = true; try { const fields = Object.fromEntries(new FormData(form)); await uploadPrivateFile(form.elements.file.files[0], 'investor-room/music/', { kind:'music', ...fields }, '#music-notice'); notice('#music-notice', 'Private upload completed. Library is updating…', true); form.reset(); setTimeout(refresh, 1200); } catch (error) { notice('#music-notice', error.message); } finally { button.disabled = false; } });
$('#global-form').addEventListener('submit', async (event) => { event.preventDefault(); const form = event.currentTarget; const button = form.querySelector('button'); button.disabled = true; try { const fields = Object.fromEntries(new FormData(form)); const base = { globalId:crypto.randomUUID(), country:fields.country, name:fields.name, position:fields.position, role:fields.role, shortBio:fields.shortBio, displayOrder:0 }; await uploadPrivateFile(form.elements.profilePdf.files[0], 'investor-room/global-profiles/', { kind:'global-pdf', ...base }, '#global-notice'); if (form.elements.profilePhoto.files[0]) await uploadPrivateFile(form.elements.profilePhoto.files[0], 'investor-room/global-photos/', { kind:'global-photo', ...base }, '#global-notice'); notice('#global-notice', 'Private uploads completed. Representative is updating…', true); form.reset(); setTimeout(refresh, 1200); } catch (error) { notice('#global-notice', error.message); } finally { button.disabled = false; } });
document.addEventListener('click', async (event) => { const button = event.target.closest('button[data-id]'); if (!button) return; try { if (button.matches('.replace-music, .replace-profile-pdf, .replace-profile-photo')) return replaceFile(button); if (button.matches('.edit-music')) { const title = prompt('Track title', button.dataset.title); if (title === null) return; const genre = prompt('Genre', button.dataset.genre); if (genre === null) return; const slug = prompt('Stable QR slug', button.dataset.slug); if (slug === null) return; await request(`/api/admin/music?id=${encodeURIComponent(button.dataset.id)}`, { method:'PATCH', headers:{'Content-Type':'application/json'}, body:JSON.stringify({title,genre,slug}) }); } else if (button.matches('.edit-global')) { const country = prompt('Country', button.dataset.country); if (country === null) return; const name = prompt('Name', button.dataset.name); if (name === null) return; await request(`/api/admin/global?id=${encodeURIComponent(button.dataset.id)}`, { method:'PATCH', headers:{'Content-Type':'application/json'}, body:JSON.stringify({country,name}) }); } else if (button.matches('.revoke-code')) { const confirmation = prompt('Type REVOKE to invalidate this access code.'); if (confirmation !== 'REVOKE') return; await request(`/api/admin/codes?id=${encodeURIComponent(button.dataset.id)}`, { method:'PATCH', headers:{'Content-Type':'application/json'}, body:JSON.stringify({action:'revoke',confirmation}) }); } else { if (!confirm('Continue?')) return; if (button.matches('.delete-music')) await request(`/api/admin/music?id=${encodeURIComponent(button.dataset.id)}`, { method:'DELETE'}); if (button.matches('.delete-global')) await request(`/api/admin/global?id=${encodeURIComponent(button.dataset.id)}`, { method:'DELETE'}); } await refresh(); } catch (error) { alert(error.message); } });
$('#admin-logout').addEventListener('click', async () => { await fetch('/api/auth?role=admin&action=logout', {method:'POST'}); location.reload(); });
try { enterApp(await request('/api/auth?role=admin&action=session')); } catch { /* unauthenticated login is intentional */ }
